name: DTI_TT
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - python=3.10.14
  - pip:
    - deeppurpose==0.1.5
    - dgl
    - gpytorch==1.12
    - ipython==8.27.0
    - matplotlib==3.9.2
    - numpy==1.26.4
    - pandas==2.2.2
    - rdkit==2024.3.5
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - torch==2.4.0